### ISSUE TITLE
提供了一种绕过反射检查从而使用jdk.internal.misc.Unsafe的简便方法

### ISSUE THREAD

**Issue by me0106** [MeiVinEight/ReflectionFX#3]
https://zhouxi.me

**Comment by iceBear67** [comment]
无法访问了呢

**Comment by me0106** [comment]
> 无法访问了呢

之前路子走的比较野，不值得看了。

在看netty源码的时候发现可以这样拿unsafe，类位置是：`io.netty.util.internal.PlatformDependent0`. 重点是`AccessController.doPrivileged()`

![image](https://user-images.githubusercontent.com/22869648/121803998-a87e7880-cc76-11eb-9aeb-6a346b2fe880.png)

**Comment by MeiVinEight** [comment]
1. ReflectionFX使用的`sun.misc.Unsafe`获取和这里的完全一样
2. JDK13之后的`AccessibleObject#override`字段加入了反射过滤，用`Field#getDeclaredField(String)`也获取不到，`AccessController.doPrivileged()`亦然
3. 使用Unsafe只能做到反射获取和修改字段，不能调用方法，如2所说，也不能代替`AccessibleObject#setAccessible(boolean)`
4. jdk.internal.misc包没有export或open给外部模块，不能在开发时直接引用，而只能用Object类型接收，因此在实际开发中也需要用反射调用其中的方法，非常麻烦

**Comment by me0106** [comment]
这样嘛，

那简单来搞就只能通过`sun.misc.Unsafe`改掉caller的module(伪装成java.base或者其他的module)。
修改override的话,反射调用setAccessible0()。
并且caller可以直接反射调用未export的public的方法了。
毕竟反射检查基本上针对module。

**Comment by MeiVinEight** [comment]
`java.lang.reflect.Proxy`类会让被实现的接口所在的包export到proxy类所在的模块，于是可以在代码中直接访问而没有模块访问限制。
[`ModuleAccess`](https://github.com/MeiVinEight/ReflectionFX/blob/master/src/main/java/org/mve/invoke/ModuleAccess.java)类会先用`java.lang.reflect.Proxy`类开启`jdk.internal.access`包的访问权限，之后在proxy对象的包中生成一个中间类，用来调用`JavaLangAccess`的一些方法来实现后续操作。
`sun.misc.Unsafe`移除后会用这种方法实现RFX。
